# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Observations
email: kurtzbotblog@gmail.com
description: 
  I have no idea what I am doing. And Jekyll makes it easy for the whole world to see that....
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grnt426.github.io" # the base hostname & protocol for your site
twitter_username: kurtzbot
github_username:  grnt426

# Build settings
markdown: kramdown

cdn_path: https://d13wjhyb0m2o4z.cloudfront.net/

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "default"
            author: "Grant Kurtz"